function getCart(){return JSON.parse(localStorage.getItem("spazaCart")||"[]");}
function saveCart(c){localStorage.setItem("spazaCart",JSON.stringify(c));updateCartCount();}
function updateCartCount(){const el=document.getElementById("cartCount");if(el)el.textContent=getCart().reduce((n,x)=>n+Number(x.qty||0),0);}
function showToast(m){let t=document.getElementById("spazaToast");if(!t){t=document.createElement("div");t.id="spazaToast";t.style.cssText="position:fixed;right:20px;bottom:20px;z-index:9999;padding:14px 18px;border-radius:12px;background:#111;color:#fff";document.body.appendChild(t)}t.textContent=m;t.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.hidden=true,2200)}
function addToCart(productId,sellerIndex=0){const p=PRODUCTS.find(x=>String(x.id)===String(productId));if(!p||!p.sellers.length)return showToast("This product currently has no active seller offer.");const s=p.sellers[sellerIndex]||p.sellers[0],c=getCart(),key=`${p.id}-${s.offerId}`;const f=c.find(x=>x.key===key);if(f)f.qty++;else c.push({key,productId:p.id,name:p.name,seller:s.name,price:Number(s.price),qty:1,offerId:s.offerId,dbProductId:p.id,sellerId:s.sellerId});saveCart(c);showToast(`${p.name} was added to your cart.`)}
function changeCartQty(i,d){const c=getCart();if(!c[i])return;c[i].qty=Math.max(1,Number(c[i].qty)+d);saveCart(c);renderCart()}
function removeCart(i){const c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function clearCart(){saveCart([]);renderCart()}
function wishlist(){return JSON.parse(localStorage.getItem("spazaWishlist")||"[]")}
function isWishlisted(id){return wishlist().includes(String(id))}
function toggleWishlist(id){const w=wishlist(),k=String(id),i=w.indexOf(k);if(i>=0)w.splice(i,1);else w.push(k);localStorage.setItem("spazaWishlist",JSON.stringify(w));renderShop();renderFeatured();renderProduct();showToast(i>=0?"Removed from wishlist":"Added to wishlist")}
function renderFeatured(){const e=document.getElementById("featuredProducts");if(!e)return;e.innerHTML=PRODUCTS.length?PRODUCTS.slice(0,6).map(card).join(""):`<div class="empty"><h3>No products are currently listed</h3><p>Approved sellers will appear here after they publish products.</p></div>`}
function renderShop(){const e=document.getElementById("shopProducts");if(!e)return;const p=new URLSearchParams(location.search),cat=p.get("category")||"all",deals=p.get("deals")==="true",search=((document.getElementById("searchInput")?.value)||p.get("q")||"").toLowerCase(),category=document.getElementById("categoryFilter")?.value||cat,rating=Number(document.getElementById("ratingFilter")?.value||0),sort=document.getElementById("sortFilter")?.value||"featured";let list=PRODUCTS.filter(x=>(category==="all"||x.category===category)&&(!search||`${x.name} ${x.category} ${x.brand}`.toLowerCase().includes(search)));if(deals)list=list.filter(x=>x.sellers.some(s=>s.price<x.price));if(sort==="priceAsc")list.sort((a,b)=>a.price-b.price);if(sort==="priceDesc")list.sort((a,b)=>b.price-a.price);if(rating)list=list.filter(x=>x.rating>=rating);e.innerHTML=list.length?list.map(card).join(""):`<div class="empty"><h3>No products found</h3><p>The live catalogue has no matching active offers.</p></div>`;const c=document.getElementById("resultCount");if(c)c.textContent=`${list.length} products`}
function renderProduct(){const e=document.getElementById("productDetails");if(!e||!PRODUCTS.length)return;const id=new URLSearchParams(location.search).get("id"),p=PRODUCTS.find(x=>String(x.id)===String(id));if(!p){e.innerHTML='<div class="empty"><h2>Product not found</h2><p>This product is not currently active.</p><a class="btn primary" href="shop.html">Back to Shop</a></div>';return}const min=Math.min(...p.sellers.map(s=>s.price));e.innerHTML=`<div class="product-main"><div class="big-product-image">${p.image?`<img src="${p.image}" alt="${p.name}">`:p.emoji}</div><div class="product-summary"><small>${p.brand?`${p.brand} · `:""}${p.category}</small><h1>${p.name}</h1><button class="btn small" onclick="toggleWishlist('${p.id}')">${isWishlisted(p.id)?"♥ Saved":"♡ Wishlist"}</button><p class="description">${p.description||"Product details supplied by the marketplace catalogue."}</p><div class="product-tabs"><button class="tab active" onclick="setProductTab(this,'overview')">Overview</button><button class="tab" onclick="setProductTab(this,'specs')">Specifications</button><button class="tab" onclick="setProductTab(this,'reviews')">Reviews</button><button class="tab" onclick="setProductTab(this,'sellers')">Sellers (${p.sellers.length})</button></div><div id="productTabContent" class="application-card"><h3>Overview</h3><p>Compare active seller offers below.</p></div><div class="offer-box"><div><small>Starting from</small><strong>${money(min)}</strong></div><button class="btn primary" onclick="addToCart('${p.id}',${p.sellers.findIndex(s=>s.price===min)})">Add lowest-price offer →</button></div></div></div><section class="seller-section"><div class="section-title"><div><p class="eyebrow">COMPARE OFFERS</p><h2>Choose your seller</h2></div><span>${p.sellers.length} active offer${p.sellers.length===1?"":"s"}</span></div><div class="seller-list">${p.sellers.map((s,i)=>`<div class="seller-offer"><div><strong>${s.name}</strong><div class="rating">${s.rating?stars(s.rating):""} <small>${s.rating||"No seller rating yet"}</small></div></div><div><strong class="offer-price">${money(s.price)}</strong><small>${s.stock===null?"Stock shown after seller inventory is available":`${s.stock} in stock`} · ${s.delivery}</small></div><button class="btn primary small" onclick="addToCart('${p.id}',${i})">Buy from seller</button></div>`).join("")}</div></section>`}
function setProductTab(b,t){document.querySelectorAll(".product-tabs .tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");const m={overview:["Overview","Compare active seller price, stock, delivery and returns."],specs:["Specifications","Specifications supplied with the live catalogue product."],reviews:["Reviews","Customer reviews are displayed here when verified reviews exist."],sellers:["Sellers","Compare each active seller offer for this product."]}[t],e=document.getElementById("productTabContent");if(e)e.innerHTML=`<h3>${m[0]}</h3><p>${m[1]}</p>`}
function renderCart(){const e=document.getElementById("cartItems");if(!e)return;const c=getCart();if(!c.length){e.innerHTML='<div class="empty"><h2>Your cart is empty</h2><a class="btn primary" href="shop.html">Start shopping</a></div>';return}const total=c.reduce((s,x)=>s+Number(x.price)*Number(x.qty),0);e.innerHTML=`<div class="cart-layout"><div>${c.map((x,i)=>`<div class="cart-item"><div class="cart-icon">🛍️</div><div style="flex:1"><strong>${x.name}</strong><small>Seller: ${x.seller}</small><div>${money(x.price)} × ${x.qty}</div><div class="qty-controls"><button onclick="changeCartQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="changeCartQty(${i},1)">+</button></div></div><button onclick="removeCart(${i})">Remove</button></div>`).join("")}</div><aside class="summary"><h3>Order summary</h3><div><span>Subtotal</span><strong>${money(total)}</strong></div><div><span>Delivery</span><span>Calculated at checkout</span></div><hr><div><strong>Total</strong><strong>${money(total)}</strong></div><a class="btn primary full" href="checkout.html">Proceed to checkout</a><button class="btn full" onclick="clearCart()">Clear cart</button></aside></div>`}
function setupMenu(){const b=document.getElementById("menuBtn"),d=document.getElementById("drawer"),o=document.getElementById("overlay"),c=document.getElementById("closeMenu");if(!b||!d)return;const close=()=>{d.classList.remove("open");o?.classList.remove("show")};b.onclick=()=>{d.classList.add("open");o?.classList.add("show")};c&&(c.onclick=close);o&&(o.onclick=close)}
function setupSearch(){const b=document.getElementById("searchBtn");if(b)b.onclick=()=>{const q=document.getElementById("searchInput")?.value||"",c=document.getElementById("categorySearch")?.value||"all";let u="shop.html";if(q||c!=="all")u+=`?${q?`q=${encodeURIComponent(q)}`:""}${q&&c!=="all"?"&":""}${c!=="all"?`category=${encodeURIComponent(c)}`:""}`;location.href=u}}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();setupMenu();setupSearch();renderFeatured();renderShop();renderProduct();renderCart()});