function checkoutCart(){return JSON.parse(localStorage.getItem('spazaCart')||'[]');}
function checkoutMoney(n){return 'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function cartPayload(c){return c.map(x=>({offer_id:x.offerId,quantity:Number(x.qty)}));}
async function startCheckout(){
 const box=document.getElementById('checkoutBox'),cart=checkoutCart();
 if(!cart.length){box.innerHTML='<div class="empty"><h2>Your cart is empty</h2><a class="btn primary" href="shop.html">Shop Now</a></div>';return;}
 const user=await getCurrentUser().catch(()=>null);if(!user){box.innerHTML='<div class="empty"><h2>Sign in required</h2><p>Please sign in before checking out.</p><a class="btn primary" href="auth-choice.html">Sign In</a></div>';return;}
 const sellers=[...new Map(cart.map(x=>[x.sellerId,{id:x.sellerId,name:x.seller}]).filter(([k])=>k)).values()];if(!sellers.length){box.innerHTML='<div class="empty"><h2>Seller information missing</h2><p>Please add a current seller offer.</p></div>';return;}
 const r=await SpazaDB.from('delivery_methods').select('id,name,method_type,description,is_active').eq('is_active',true).order('name');if(r.error){box.innerHTML='<div class="empty"><h2>Delivery options unavailable</h2><p>'+esc(r.error.message)+'</p></div>';return;}const methods=r.data||[];
 const subtotal=cart.reduce((s,x)=>s+Number(x.price)*Number(x.qty),0);
 box.innerHTML=`<div class="cart-layout"><section><div class="application-card"><h2>Delivery & contact details</h2><form id="checkoutForm"><input id="recipient" required placeholder="Recipient name" value="${esc(user.user_metadata?.full_name||'')}"><input id="phone" required placeholder="Phone number"><input id="address1" required placeholder="Street address"><input id="suburb" placeholder="Suburb"><input id="city" required placeholder="City"><input id="province" placeholder="Province"><input id="postal" placeholder="Postal code"><textarea id="instructions" placeholder="Delivery instructions"></textarea><h3>Fulfilment</h3>${sellers.map(s=>`<label>${esc(s.name)}<select class="seller-method" data-seller="${esc(s.id)}">${methods.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label>`).join('')}<button class="btn secondary" type="button" id="quoteBtn">Calculate delivery</button><p id="checkoutMsg"></p><div id="quoteResult"></div><button class="btn primary" id="placeOrderBtn" type="submit" disabled>Place order & continue to payment</button></form></div></section><aside class="summary"><h3>Order summary</h3>${cart.map(x=>`<div><span>${esc(x.name)} × ${x.qty}</span><strong>${checkoutMoney(Number(x.price)*Number(x.qty))}</strong></div>`).join('')}<hr><div><strong>Subtotal</strong><strong>${checkoutMoney(subtotal)}</strong></div><div><span>Delivery</span><strong id="deliveryTotal">—</strong></div><div><strong>Total</strong><strong id="grandTotal">${checkoutMoney(subtotal)}</strong></div></aside></div>`;
 const address=()=>({recipient_name:document.getElementById('recipient').value,phone:document.getElementById('phone').value,address_line_1:document.getElementById('address1').value,suburb:document.getElementById('suburb').value,city:document.getElementById('city').value,province:document.getElementById('province').value,postal_code:document.getElementById('postal').value,country:'South Africa',delivery_instructions:document.getElementById('instructions').value});
 const selections=()=>[...document.querySelectorAll('.seller-method')].map(s=>({offer_id:cart.find(x=>String(x.sellerId)===String(s.dataset.seller))?.offerId,delivery_method_id:s.value}));
 const fulfilments=()=>Object.fromEntries([...document.querySelectorAll('.seller-method')].map(s=>[s.dataset.seller,{delivery_method_id:s.value}]));let quote=null;
 document.getElementById('quoteBtn').onclick=async()=>{const msg=document.getElementById('checkoutMsg');msg.textContent='Calculating delivery…';try{const {data,error}=await SpazaDB.rpc('quote_customer_delivery',{p_cart:cartPayload(cart),p_selections:selections(),p_address:address()});if(error)throw error;quote=data;const fee=Number(data.delivery_total||0);document.getElementById('deliveryTotal').textContent=checkoutMoney(fee);document.getElementById('grandTotal').textContent=checkoutMoney(subtotal+fee);document.getElementById('quoteResult').innerHTML='<div class="notice"><strong>Delivery quote ready</strong><span>Server-calculated delivery: '+checkoutMoney(fee)+'</span></div>';document.getElementById('placeOrderBtn').disabled=false;msg.textContent=''}catch(e){quote=null;document.getElementById('placeOrderBtn').disabled=true;msg.textContent=e.message||'Unable to calculate delivery.'}};
 document.getElementById('checkoutForm').onsubmit=async e=>{e.preventDefault();const msg=document.getElementById('checkoutMsg'),btn=document.getElementById('placeOrderBtn');if(!quote){msg.textContent='Calculate delivery before placing the order.';return}btn.disabled=true;msg.textContent='Creating order…';try{const {data:order,error}=await SpazaDB.rpc('create_customer_order',{p_cart:cartPayload(cart),p_contact:{name:document.getElementById('recipient').value,phone:document.getElementById('phone').value,email:user.email},p_delivery_address:address(),p_fulfilments:fulfilments(),p_customer_notes:document.getElementById('instructions').value||null});if(error)throw error;if(!order?.order_id)throw new Error('Order was not created.');const {data:session,error:se}=await SpazaDB.rpc('create_customer_payment_session',{p_amount:Number(order.grand_total),p_currency:'ZAR',p_idempotency_key:'SPZ-ORDER-'+order.order_id,p_metadata:{order_id:order.order_id,order_number:order.order_number}});if(se)throw se;const {error:be}=await SpazaDB.rpc('bind_payment_session_to_order',{p_session_id:session.id,p_order_id:order.order_id});if(be)throw be;localStorage.removeItem('spazaCart');location.href='payment.html?session='+encodeURIComponent(session.id)+'&order='+encodeURIComponent(order.order_number)}catch(err){console.error(err);btn.disabled=false;msg.textContent=err.message||'Order creation failed.'}};
}
document.addEventListener('DOMContentLoaded',startCheckout);